# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x0bPostRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0cPostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1b\n\nGetRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x0bGetResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xde\x01\n\x0b\x43hatService\x12\x30\n\x05Login\x12\x12.chat.LoginRequest\x1a\x13.chat.LoginResponse\x12\x33\n\x06Logout\x12\x13.chat.LogoutRequest\x1a\x14.chat.LogoutResponse\x12\x34\n\x0bPostMessage\x12\x11.chat.PostRequest\x1a\x12.chat.PostResponse\x12\x32\n\x0bGetMessages\x12\x10.chat.GetRequest\x1a\x11.chat.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_LOGINRESPONSE']._serialized_start=72
  _globals['_LOGINRESPONSE']._serialized_end=119
  _globals['_LOGOUTREQUEST']._serialized_start=121
  _globals['_LOGOUTREQUEST']._serialized_end=151
  _globals['_LOGOUTRESPONSE']._serialized_start=153
  _globals['_LOGOUTRESPONSE']._serialized_end=186
  _globals['_POSTREQUEST']._serialized_start=188
  _globals['_POSTREQUEST']._serialized_end=233
  _globals['_POSTRESPONSE']._serialized_start=235
  _globals['_POSTRESPONSE']._serialized_end=266
  _globals['_GETREQUEST']._serialized_start=268
  _globals['_GETREQUEST']._serialized_end=295
  _globals['_GETRESPONSE']._serialized_start=297
  _globals['_GETRESPONSE']._serialized_end=328
  _globals['_CHATSERVICE']._serialized_start=331
  _globals['_CHATSERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
