# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\",\n\nLLMRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"\x1d\n\x0bLLMResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2?\n\nLLMService\x12\x31\n\x0cGetLLMAnswer\x12\x0f.llm.LLMRequest\x1a\x10.llm.LLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=18
  _globals['_LLMREQUEST']._serialized_end=62
  _globals['_LLMRESPONSE']._serialized_start=64
  _globals['_LLMRESPONSE']._serialized_end=93
  _globals['_LLMSERVICE']._serialized_start=95
  _globals['_LLMSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
